TASK=SST2
SPARSITY=0.4
PRUNE_LOCATION=2,3,4,5,6,7,8,9,10,11
LEARNING_RATE=1e-5
REG_LEARNING_RATE=0.02
DISTILL_RANK_LOSS_ALPHA=0.01
WARMUP_EPOCHS=10
BIN_NUM=25
TOPK=20
EPOCHS=40
EVAL_STEP=100
SUFFIX=s${SPARSITY}_lr${LEARNING_RATE}_reglr${REG_LEARNING_RATE}_alpha${DISTILL_RANK_LOSS_ALPHA}_warmup${WARMUP_EPOCHS}_bin${BIN_NUM}
EX_CATE=run_fix
# token pruning
PRUNING_TYPE=token+pruner
SPARSITY_EPSILON=0.01
DISTILLATION_PATH=senfu/bert-base-uncased-finetuned-sst2

script_file=run_TokenPrune.sh
DISTILL_LAYER_LOSS_ALPHA=0.9 # not used. ignore this parameter
LAYER_DISTILL_VERSION=4 # not used. ignore this parameter


bash scripts/${script_file} $TASK $SUFFIX $EX_CATE $PRUNING_TYPE $SPARSITY $DISTILLATION_PATH $DISTILL_LAYER_LOSS_ALPHA $DISTILL_RANK_LOSS_ALPHA $LAYER_DISTILL_VERSION $SPARSITY_EPSILON $PRUNE_LOCATION $LEARNING_RATE $REG_LEARNING_RATE $WARMUP_EPOCHS $BIN_NUM $TOPK $EPOCHS $EVAL_STEP
